### ISSUE TITLE
Historical Data?

### ISSUE THREAD

**Issue by daven1985** [troykelly/homeassistant-au-nsw-covid#23]
Good morning,

Again I am loving this states you have made available. Is it possible to have any history with the data? Would be good for active cases etc to be able to use a graph and show previous days options.

I understand if this is not possible.

**Comment by troykelly** [comment]
Sorry, @daven1985 - HA has no concept of "historical data" - I'd love this too for power use monitoring and a few other things.

The only way to build up the historical data is by having the sensor active. As the days progress - you will build up your own historical dataset that can be charted, used with the [statistical tools](https://www.home-assistant.io/integrations/statistics/) for trending, or whatever you want to do with them.

As you can see below - I've now got two days of "historical" data - by the end of the lockdown, I will have the full six months of it (I joke... well, I hope I'm joking)

<img width="393" alt="Screen Shot 2021-08-03 at 12 51 55 pm" src="https://user-images.githubusercontent.com/4564803/127950125-9b5e0345-c5ff-4297-b10c-c041546b076b.png">
