### ISSUE TITLE
Error on v6

### ISSUE THREAD

**Issue by daven1985** [troykelly/homeassistant-au-nsw-covid#3]
Just updated… getting this error.

When I search for it in Integrations (after updating in HACS). **Config flow could not be loaded**

And then in my notifications I get the following: 

_The following integrations and platforms could not be set up:
nswcovid==0.0.6_

<blockquote class="imgur-embed-pub" lang="en" data-id="a/ZlS65fp" data-context="false" ><a href="//imgur.com/a/ZlS65fp"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by troykelly** [comment]
Yeah - still waiting on approval for the library.
More information in #2
