### ISSUE TITLE
Errors in the logs referring to 'NoneType'

### ISSUE THREAD

**Issue by nickh66** [troykelly/homeassistant-au-nsw-covid#44]
Hi,

Firstly, thanks for making this integration. Great work. 
I thought i would share some error details i'm seein my log today.  In case it's something that you can fix.

2021-08-30 11:02:47 ERROR (MainThread) [nswcovid.protocol.statistics] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/nswcovid/protocol/statistics.py", line 185, in details
value = pyquery(list_dict_data, statistic.json_search)
File "/usr/local/lib/python3.9/site-packages/jello/lib.py", line 396, in pyquery
_θ_output = eval(compile(_θ_last, '<string>', mode='eval'))
File "<string>", line 1, in <module>
File "<string>", line 1, in <listcomp>
TypeError: argument of type 'NoneType' is not iterable

Cheers
Nick

**Comment by troykelly** [comment]
Thank you for letting me know @nickh66 
I will have to have a look this evening and see if I can reproduce.
I'm guessing for some reason there is missing data coming into [here](https://github.com/troykelly/python-nswcovid/blob/5d98632e0c3e2ac0d2b5f7bae60a2aec0acf5c25/src/nswcovid/protocol/statistics.py#L185) and I'm not handling that properly.

**Comment by nickh66** [comment]
I wish i could help but sadly i don't yet have the python skills.

**Comment by DavidFW1960** [comment]
2021.9.0b6 isn't happy either..
```
2021-08-31 09:10:30 ERROR (MainThread) [nswcovid.protocol.statistics] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nswcovid/protocol/statistics.py", line 185, in details
    value = pyquery(list_dict_data, statistic.json_search)
  File "/usr/local/lib/python3.9/site-packages/jello/lib.py", line 396, in pyquery
    _θ_output = eval(compile(_θ_last, '<string>', mode='eval'))
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
TypeError: argument of type 'NoneType' is not iterable
2021-08-31 09:10:30 ERROR (MainThread) [nswcovid.protocol.statistics] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nswcovid/protocol/statistics.py", line 185, in details
    value = pyquery(list_dict_data, statistic.json_search)
  File "/usr/local/lib/python3.9/site-packages/jello/lib.py", line 396, in pyquery
    _θ_output = eval(compile(_θ_last, '<string>', mode='eval'))
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
TypeError: argument of type 'NoneType' is not iterable
```
Lots of those

**Comment by troykelly** [comment]
Yeah - I've messed something up with the JSON processing - I'm just struggling to work out what I've done wrong.
Will get back to it shortly.
It's an issue in the library: https://github.com/troykelly/python-nswcovid/issues/41

**Comment by troykelly** [comment]
Okay, adding `data.ageGroup is not None` to the tests to prevent the `None` being incorrectly handled.
Updating the library now
https://github.com/troykelly/python-nswcovid/pull/42/files#diff-1febc096fb599167641dc4e282f516a284a6c77d61cbcb6aa629ff1c634ecd3a

**Comment by troykelly** [comment]
@nickh66 @DavidFW1960 Thank you both, I've tested in dev and on my personal setup - looks like it is fixed.
Let me know if there are any issues.

**Comment by DavidFW1960** [comment]
looks ok but now I see this:
```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:213
Integration: Sensor (documentation, issues)
First occurred: 12:57:14 PM (9 occurrences)
Last logged: 12:57:14 PM

Entity sensor.covid_nsw_last_24_hours_total (<class 'custom_components.nswcovid.sensor.NSWCovidEntry'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
Entity sensor.covid_nsw_last_24_hours_tests (<class 'custom_components.nswcovid.sensor.NSWCovidEntry'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
Entity sensor.covid_nsw_last_24_hours_first_dose_vaccine (<class 'custom_components.nswcovid.sensor.NSWCovidEntry'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
Entity sensor.covid_nsw_last_24_hours_second_dose_vaccine (<class 'custom_components.nswcovid.sensor.NSWCovidEntry'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
Entity sensor.covid_nsw_last_24_hours_vaccine_total (<class 'custom_components.nswcovid.sensor.NSWCovidEntry'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
```

**Comment by troykelly** [comment]
This statistics / last_reset thing is going to be the death of me.
Thank you @DavidFW1960 - I will raise a separate issue for it.
